# Generated by Django 4.2 on 2025-04-27 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=1234, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
    ]
